version: "3.9"

services:
  telemeter:
    build:
      context: ./telemeter
      dockerfile: dockerfile
    container_name: watcher-dev
    networks:
      - smartops-network

  detector:
    build:
      context: ./agent-service/
      dockerfile: agents/detector/Dockerfile
    container_name: smartops-detector
    ports:
      - "8001:8001"
    networks:
      - smartops-network

  rca:
    build:
      context: ./agent-service
      dockerfile: agents/rca_brain/Dockerfile
    container_name: smartops-rca
    ports:
      - "8002:8002"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - smartops-network

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_INIT_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_INIT_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - smartops-network

  orchestrator:
    build:
      context: ./agent-service/
      dockerfile: agents/orchestrator/Dockerfile
    container_name: smartops-orchestrator
    ports:
      - "8000:8000"
    depends_on:
      - detector
      - rca
      - influxdb
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_ORG=${INFLUX_INIT_ORG}
      - INFLUX_BUCKET=${INFLUX_INIT_BUCKET}
      - INFLUX_TOKEN=${INFLUX_INIT_TOKEN}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
    networks:
      - smartops-network

  observer:
    build:
      context: ./observer
      dockerfile: dockerfile
    container_name: observer
    ports:
      - "80:80"
    depends_on:
      - orchestrator
    networks:
      - smartops-network

networks:
  smartops-network:
    driver: bridge

volumes:
  influxdb_data:
