FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    make \
    build-essential \
    procps \
    && rm -rf /var/lib/apt/lists/*

COPY . /app

RUN pip install --no-cache-dir requests

RUN make -C telemeter/agent clean && \
    make -C telemeter/agent

RUN chmod +x telemeter/entrypoint.sh

ENTRYPOINT ["/app/telemeter/entrypoint.sh"]
